### ISSUE TITLE
Potions with unselected effect

### ISSUE THREAD

**Issue by LadivItnas** [ate47/AdvancedCreativeTab#1]
I wanted to make a potion with the night vision potion skin, and with speed 127. So I put "127" in Swiftness and set the time to 83000. I named it and clicked on the night vision potion visual. And when I clicked give, I had a swiftness visual with a random night vision effect.
![2017-03-03_21 38 04](https://cloud.githubusercontent.com/assets/26176267/23574238/3f5714fc-005b-11e7-961f-afb0fec1d7b8.png)

**Comment by ate47** [comment]
Fix in 2.0.
