### ISSUE TITLE
Issues with AdvancedCreativeTab

### ISSUE THREAD

**Issue by taylormather** [ate47/AdvancedCreativeTab#12]
1. The Potion editor can crash your entire Minecraft just by clicking on the Potion Editor button
2. Saving hot bars of enchanted items you enchanted with AdvancedCreativeTab kick you out of servers

As a griefer, I am very sad about these bugs :(

**Comment by Darko1green1LOrd** [comment]
Potion Editor crashes you only when you open edited potion with it and the kick never happens + as griefer you can spawn entities on some coords for example spawning nuke-tnt on 21 23 444    i make lot of custom items in the mod and i have lot of them made

**Comment by ate47** [comment]
Fixed the potion editor bug in the 1.16 update, I guess the problem with the kick is due to an anti-cheat kicking you for a too high CustomPayLoadPacket size, I can't fix that, if the error isn't that, re-open the issue.
