### ISSUE TITLE
v2.6.0 incompatible with Optifine/Optiforge on MC 1.17.1 "encountered an error during the common_setup event phase"

### ISSUE THREAD

**Issue by AlcyonNorthstar** [ate47/AdvancedCreativeTab#14]
Testing mod version 2.6.0 on Forge 37.0.59 (crash report attached).  Without Optifine and Optiforge installed, it works fine.

With [OptiFine_1.17.1_HD_U_G9](https://optifine.net/home) and [OptiForge-MC1.17.1-0.1.0.jar](https://www.curseforge.com/minecraft/mc-mods/optiforge), it crashes during MC mod load with "encountered an error during the common_setup event phase" message.

[crash-2021-09-12_09.58.40-fml.txt](https://github.com/ate47/AdvancedCreativeTab/files/7149849/crash-2021-09-12_09.58.40-fml.txt)

**Comment by ate47** [comment]
fixed in #16
