### ISSUE TITLE
Crashed when loading

### ISSUE THREAD

**Issue by zcn15** [ate47/AdvancedCreativeTab#16]
Minecraft version 1.18.1, forge: 39.0.44
Error: "Mod loading error has occurred"

[crash-2022-01-19_11.55.07-fml.txt](https://github.com/ate47/AdvancedCreativeTab/files/7896054/crash-2022-01-19_11.55.07-fml.txt)
4

**Comment by ate47** [comment]
You can download the fixed 1.18 version via the CurseForge launcher or [here](https://www.curseforge.com/minecraft/mc-mods/advanced-extended-creative-mode/files/3613281) (Modrinth will be available soon)

**Comment by zcn15** [comment]
Its working now, great mod. Thanks!
