### ISSUE TITLE
Seriously NEEDED: way to remove items from the 'Custom Item' tab!  [fills up becoming useless]

### ISSUE THREAD

**Issue by Jill-Kitten** [ate47/AdvancedCreativeTab#2]
Is there no way to remove items from the "Custom Item" [and "Unreal Items"] tab(s)?  I can add items but then I can never remove them, eventually it will run out of space!

I already have it half full and most of the items are old items I don't need anymore [superseded by newer items] just unnecessarily eating up space, again eventually it will run out of space and then will become useless.

Thus it would be really nice to be able to customize those, and unfortunately I cannot seem to remove any item that I create in the Custom Item tab.

Is there maybe a way to edit a file somewhere to remove specific items if even in a dangerous manual way?  In any case, there really seriously NEEDS to be a way to remove items from the 'Custom Item' tab!

**Comment by ate47** [comment]
Shift + Right Click in ACT2.0 or from the giver with the delete button.
